### ISSUE TITLE
XSPEC Error: Unknown table format: check identifiers

### ISSUE THREAD

**Issue by mbelveder** [AtsushiTanimoto/XClumpy#2]
Hi!

I got a problem reading your model. My HEASOFT version is 6.31.1. Can you please provide some comments?

<img width="1481" alt="image" src="https://github.com/AtsushiTanimoto/XClumpy/assets/43069139/f40de7e2-6dec-4baf-8d2b-968f61b0f31a">

**Comment by AtsushiTanimoto** [comment]
Thank you for using our model.

> Can you please provide some comments?

To use these models, you need to put files such as xclumpy_v01_RC.fits and xclumpy_V01_RL.fits in the same directory. Could you please check if these files exist in the working directory?

**Comment by mbelveder** [comment]
Yep, they are there:

<img width="1205" alt="image" src="https://github.com/AtsushiTanimoto/XClumpy/assets/43069139/0f5a1561-3b78-44ca-8e69-6531ec887ea4">

I've also tried it on several different machines with slightly different XSPEC versions but couldn't check it with the same one you used in your work (6.24).

**Comment by AtsushiTanimoto** [comment]
Thank you for your reply.

> Yep, they are there:

OK. Thank you for your confirmation.

> I've also tried it on several different machines with slightly different XSPEC versions but couldn't check it with the same one you used in your work (6.24).

Although I tried to see if these models could be loaded with Heasoft 6.33.2 (XSPEC 12.14.0h), I could not reproduce your error (Mac OS 14.4.1). Updating Heasoft to the latest version may solve the problem.
